### ISSUE TITLE
Create endpoint to get user list

### ISSUE THREAD

**Issue by KWSilence** [Bluff-Boletus/Que.ue-back#12]
Endpoint like "queue/{id}" which get list of `QueuePlace` (response: current user list (active/complete), but add user login instead id)

**Comment by aleksandraprohorova** [comment]
@KWSilence @panandafog this is already implemented

**Comment by panandafog** [comment]
As i see, this endpoint returns list of queue, that does not have list of `QueuePlace` property. 🤔

`
@AllArgsConstructor
@Getter
public class GetQueueInfoResponse {
    Queue queue;
}
`

`
@Entity
@Table(name = "queues")
@Getter
@Setter
@NoArgsConstructor
public class Queue {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private int id;

    @Column(name = "admin_id")
    private int adminId;

    @Column(name = "link")
    private String link;

    @Column(name = "name")
    private String name;

    @Column(name = "opening_time")
    private LocalDateTime openingTime;

    @Column(name = "start_time")
    private LocalDateTime startTime;

    @Column(name = "total_quantity")
    private int totalQuantity;

    @Column(name = "current_number")
    private int currentNumber;

    public Queue(int adminId, String name, LocalDateTime openingTime, LocalDateTime startTime) throws QueueIllegalArgumentException {
        if (openingTime.isAfter(startTime)) {
            throw new QueueIllegalArgumentException("Time of opening queue for joining must be less than time of launching the queue.");
        }

        this.adminId = adminId;
        this.name = name;

        this.openingTime = openingTime;
        this.startTime = startTime;

        totalQuantity = 0;
        currentNumber = 0;
    }
}
`

**Comment by aleksandraprohorova** [comment]
Done
