### ISSUE TITLE
Increase user's login length to >= 28

### ISSUE THREAD

**Issue by panandafog** [Bluff-Boletus/Que.ue-back#13]
Firebase uid length is 28

**Comment by aleksandraprohorova** [comment]
@panandafog it would be reasonable just to add another column specially for firebase id and use login field just to visualize info about user

**Comment by panandafog** [comment]
> @panandafog it would be reasonable just to add another column specially for firebase id and use login field just to visualize info about user

Ok, but then u need to rename login to uid in all requests with body.
