### ISSUE TITLE
Add endpoint to search queues by admin id

### ISSUE THREAD

**Issue by panandafog** [Bluff-Boletus/Que.ue-back#16]
Now user doesn't see the queue in his queue list until he writes himself to it

**Comment by panandafog** [comment]
Now user user doesn't see the queue in his queue list until he writes himself to it

**Comment by aleksandraprohorova** [comment]
@panandafog does he really need to see the entire list of queues in which he does not participate? I will correct method getQueueInfoByUrl to make it POST instead of GET and you will have the ability to get info about particular queue by url
